AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'netflix-spectator-rb.gemspec'

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false
