Metrics/BlockLength:
  Exclude:
    - 'spectator.gemspec'

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false
  
