sudo: false
language: ruby
rvm:
- 2.5.1
before_install: gem install bundler -v 1.16.1
script: "./buildViaTravis.sh"
deploy:
  provider: rubygems
  api_key:
    secure: XGHhdcV4r3jxgL652dd+iKjkleu/djs99H4M5i3Hp1uPhv8P6lenTKnSByW3zzN37MSLbTs2NVnncnj5zOBnVYQf/0gok3cki9Qj/7m4XyOx5irn1dWR/MwuuWuzVU1DxDz8+27f8yNs8uz6b4dlDdI4aa5qQfJQW1v/lgXV+exTVoSvNPsAzE/I8v5v5n4rzycnNBx1bV0U4jfKx0vNmUKUhhQCaD1Uw77JcRvOkZYY26MD9xDf7bOMaAdAh2TSX54wvplyrjQltZsVA5/lvmR1U3ngvGnaZ3McypAB543+0MiCEdHASlJd0tFDMCC444b0Z38MWTklekEJd5OzF4s1amVD5SND5PRUqtrRonggLdszFa+Cw2tCDM5RcLQPrmcHPK6uIGn+vMmWDmmlvsFuzsxQ6Qmnur4iUh9A7c8y3Ic0b+MFxR9Er+C4xxxOS+R/C4+960/+KHKDoamcJ54FJb2JUSryXAlRkQQu9KOHplqgkUNvIb86Ekzg+em3AgsDdPQgUWhqJ4U7oTzMd0ww9K9p1Gol3UH2LkH5iOjAj/g9RhQNmMQCA3U9unqcZFCieYRhuVr4TFpRCmBOu1nuFs4g7KpUXcAifvx1A2s7DOTOyIzMsgtVIS0RcgvgfvLQArz8A696fZJ6+9YTd3jPyGZZ1gKxCw7Ep0UZw0U=
  gem: spectator-rb
  on:
    tags: true
    repo: Netflix/spectator-rb
